import './globals.css'


export const metadata = {
  title: 'F1 Visa Mock Text',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='main'>
          <div className='gradient'></div>
        </div>
        <main className='app'>
        {children}
        </main>
        </body>
    </html>
  )
}
