

const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "NAME", uid: "name", sortable: true},
  {name: "MAJOR", uid: "major"}, // which major is selected
  {name: "SCANNED DOCUMENTS", uid: "scannedDocuments"}, // documents scanned or not
  {name: "DS160", uid: "ds160"}, // ds160 form filled or not 
  {name: "INTERVIEW DATE BOOKING", uid: "interviewDateBooking"}, // interview date booked or not 
  {name: "APPLICATION", uid: "application"}, // application completed or not
  { name: "UNIVERSITY", uid: "university" },
  { name: "NUMBER", uid: "number" },
  {name: "COUNSELOR", uid: "counselor"},
  {name: "EMAIL", uid: "email"},
  {name: "APP FEE", uid: "status", sortable: true},
  {name: "VISA STATUS", uid: "visaStatus", sortable: true},
];

 const visaStatusOptions = [
  { uid: "accepted", name: "Accepted" },
  { uid: "processing", name: "Processing" },
  { uid: "rejected", name: "Rejected" },
];
const statusOptions = [
    {name: "Paid", uid: "paid"},
    {name: "Half Paid", uid: "half paid"},
    {name: "Not Paid", uid: "not paid"},
    {name: "Waived", uid: "waived"},
  ];


  const counselorOptions = [ 
    { name : 'Prakash Bhatta', uid : 'prakash bhatta'},
    { name : 'Ujjwol Dhakal', uid : 'ujjwol dhakal'},
  ];


  const universityOptions = [
    { name: 'Harvard University', uid: 'harvard-university' },
    { name: 'Stanford University', uid: 'stanford-university' },
    { name: 'Massachusetts Institute of Technology (MIT)', uid: 'mit' },
    { name: 'University of Oxford', uid: 'oxford-university' },
    { name: 'California Institute of Technology (Caltech)', uid: 'caltech' },
    // Add more universities as needed
];

const majorOptions = [
    { name: "Computer Science", uid: "computer-science" },
    { name: "Electrical Engineering", uid: "electrical-engineering" },
    { name: "Mechanical Engineering", uid: "mechanical-engineering" },
    { name: "Biology", uid: "biology" },
    { name: "Mathematics", uid: "mathematics" },
    // Add more undergraduate majors as needed
    
    { name: "Computer Science (Master's)", uid: "computer-science-master" },
    { name: "Electrical Engineering (Master's)", uid: "electrical-engineering-master" },
    { name: "Mechanical Engineering (Master's)", uid: "mechanical-engineering-master" },
    { name: "Biology (Master's)", uid: "biology-master" },
    { name: "Mathematics (Master's)", uid: "mathematics-master" },
    // Add more master's majors as needed
    
    { name: "Computer Science (Bachelor's)", uid: "computer-science-bachelor" },
    { name: "Electrical Engineering (Bachelor's)", uid: "electrical-engineering-bachelor" },
    { name: "Mechanical Engineering (Bachelor's)", uid: "mechanical-engineering-bachelor" },
    { name: "Biology (Bachelor's)", uid: "biology-bachelor" },
    { name: "Mathematics (Bachelor's)", uid: "mathematics-bachelor" },
    // Add more bachelor's majors as needed
  ];
  
  const ds160Options = [
    { name: "Filled", uid: "filled" },
    { name: "Not Filled", uid: "not-filled" },
  ];
  
  const interviewDateBookingOptions = [
    { name: "Booked", uid: "booked" },
    { name: "Not Booked", uid: "not-booked" },
  ];
  
  const applicationOptions = [
    { name: "Completed", uid: "completed" },
    { name: "Not Completed", uid: "not-completed" },
  ];
  

  const scannedDocuments = [
    { name: "Scanned", uid: "scanned" },
    { name: "Not Scanned", uid: "not-scanned" },
  ]
  
const userNumber = [
  { name: 9810359789, uid: "userNumber" },
]


const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    university: "Harvard University",
    status: "Paid",
    age: "29",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    visaStatus: 'accepted',
    interviewDateBooking: 'Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Tech Lead",
    university: "Stanford University",
    status: "Half Paid",
    age: "25",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    visaStatus: 'rejected',
    interviewDateBooking: 'Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Sr. Dev",
    university: "MIT",
    status: "Not Paid",
    age: "22",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Not Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "C.M.",
    university: "University of Oxford",
    status: "Waived",
    age: "28",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Cooper",
    role: "S. Manager",
    university: "Caltech",
    status: "active",
    age: "24",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    role: "P. Manager",
    university: "Harvard University",
    age: "29",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 7,
    name: "Michael Hunt",
    role: "Designer",
    university: "Stanford University",
    status: "paused",
    age: "27",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    role: "HR Manager",
    university: "MIT",
    status: "active",
    age: "31",
    number: 9810359789,
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Not Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    role: "F. Manager",
    university: "University of Oxford",
    status: "vacation",
    age: "33",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    role: "Ops Manager",
    university: "Caltech",
    status: "active",
    age: "35",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    role: "Jr. Dev",
    university: "Harvard University",
    status: "active",
    age: "22",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Not Filled',
    interviewDateBooking: 'Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    role: "P. Manager",
    university: "Stanford University",
    status: "paused",
    age: "28",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    role: "S. Manager",
    university: "MIT",
    status: "active",
    age: "37",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Not Filled',
    interviewDateBooking: 'Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "Grace Allen",
    role: "M. Specialist",
    university: "Caltech",
    status: "active",
    age: "30",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=16",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "Noah Carter",
    role: "IT Specialist",
    university: "University of Oxford",
    status: "paused",
    age: "31",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?img=15",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "Ava Perez",
    role: "Manager",
    university: "Harvard University",
    status: "active",
    age: "29",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Booked',
    application: 'Completed',
    avatar: "https://i.pravatar.cc/150?img=20",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "Liam Johnson",
    role: "Data Analyst",
    university: "Stanford University",
    status: "active",
    age: "28",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=33",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    role: "QA Analyst",
    university: "MIT",
    status: "active",
    age: "27",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Scanned',
    ds160: 'Not Filled',
    interviewDateBooking: 'Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=29",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "Lucas Harris",
    role: "Administrator",
    university: "University of Oxford",
    status: "paused",
    age: "32",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Filled',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=50",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "Mia Robinson",
    role: "Coordinator",
    university: "Caltech",
    status: "active",
    age: "26",
    counselor: 'Ujjwol Dhakal',
    scannedDocuments: 'Not Scanned',
    ds160: 'Not Filled',
    visaStatus: 'processing',
    interviewDateBooking: 'Not Booked',
    application: 'Not Completed',
    avatar: "https://i.pravatar.cc/150?img=45",
    email: "mia.robinson@example.com",
  },
];

export { columns, users, statusOptions, counselorOptions, universityOptions, majorOptions, ds160Options, interviewDateBookingOptions, applicationOptions, scannedDocuments, userNumber, visaStatusOptions };
